name: Build

on:
  push:
    branches: [ "master" ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Go get
        run: go get dhtc

      - name: Build Linux
        if: runner.os == 'Linux'
        run: go build -v -o dhtc-linux cmd/dhtc/main.go

      - name: Build macOS
        if: runner.os == 'macOS'
        run: go build -v -o dhtc-macos cmd/dhtc/main.go

      - name: Build Windows
        if: runner.os == 'Windows'
        run: go build -v -o dhtc-windows.exe cmd/dhtc/main.go
