name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go get .
          if [ "$RUNNER_OS" == "Linux" ]; then
            go build -v -o dhtc-linux dhtc
          elif [ "$RUNNER_OS" == "Windows" ]; then
            go build -v -o dhtc-windows.exe dhtc
          elif [ "$RUNNER_OS" == "macOS"]; then
            go build -v -o dhtc-macos dhtc
          else
            echo "$RUNNER_OS is unsupported"
            exit 1
          fi
